nameOverride:

resources:
  deployment:
  statefulset:
  storage:
  ingress:
  configMap:
  secrets:
  Cronjob:
  VirtualService:
  Gateway:

deployment:
  labels: {}
  replicas:
  image: ""
  internalPort:
  resources: {}
  env: {}
  volumeMounts: []

storage:
  storageClassName: ""
  accessModes: []
  size:
  reclaimpolicy:
  nfs:
    enabled:
    path:
    server:

service:
  type:
  port:
  nodePort:

ingress:
  enabled:
  host:
  path:
  pathType:
  ingressClassName:

configmap:
  data: {}

secrets:
  data: {}
