{{- if .Values.statefulset.create -}}
apiVersion: apps/v1
kind: StatefulSet
metadata: {{ $fullname := printf "%s-%s" .Release.Name .Chart.Name | trunc 57 | trimSuffix "-" }}
  name: {{ $fullname }}-sts
  labels:
    {{- include "helm-tutorial.labels" . | nindent 4}}
spec:
  serviceName: {{ .Values.statefulset.serviceName }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm-tutorial.selectorLabels" . | nindent 6}}
  template:
    metadata:
      labels:
        {{- include "helm-tutorial.selectorLabels" . | nindent 6}}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: "{{ .Values.containerImage.name }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.service.port | int }}
          volumeMounts:
            - name: {{ $fullname }}-data
              mountPath: {{ .Values.statefulset.mountPath }}
  volumeClaimTemplates:
    - metadata:
        name: {{- $fullname }}-data
      spec:
        accessModes: {{- .Values.storageClass.accessModes }}
        storageClassName: {{ $fullname }}-sc
        resources:
          requests:
            storage: {{ .Values.statefulset.storage }}
{{- end -}}